function SleepHomeoToDataFolder

[names,dirs]=GetDefaultDataset;

RecordingsDir = fullfile(getdropbox,'Data','Recordings');


for a = 1:length(names);
    basename = names{a};
    basepath = dirs{a};
    mkdir(fullfile(RecordingsDir,basename))
    
    ok = {[basename '.eeg'],...
        [basename '.lfp'],...
        [basename '.xml'],...
        [basename '_BasicMetaData.mat'],...
        [basename '_ChannelAnatomy.csv'],...
        [basename '_SpikeGroupAnatomy.csv'],...
        [basename '_ClusteringNotes.csv'],...
        [basename '_Header.m'],...
        [basename '_GoodSleepInterval.mat'],...
        [basename '_Motion.mat'],...
        [basename '_CellIDs.mat'],...
        [basename '_SStable_mat'],...
        [basename '_SSubtypes.mat'],...
        [basename '_funcsynapsesMoreStringent.mat'],...
        [basename '_UPDOWNIntervals.mat'],...
        [basename '_RippleData.mat'],...
        [basename '_SpindleData.mat']};
    
    d = dir(basepath);
    for b = 1:length(d);
        if strmatch(d(b).name,ok);
            eval(['! cp ' fullfile(basepath,d(b).name) ' ' fullfile(RecordingsDir,basename,d(b).name)])
        end
    end
end
