
executestring = [...
'[WSWEpisodes,WSWBestIdx] = DefineWakeSleepWakeEpisodes(intervals,GoodSleepInterval);'...
'[WSEpisodes,WSBestIdx] = DefineWakeSleepEpisodes(intervals,GoodSleepInterval);'...
'[SWEpisodes,SWBestIdx] = DefineSleepWakeEpisodes(intervals,GoodSleepInterval);'...
'save(fullfile(basepath,[basename ''_WSWEpisodes'']),''WSWEpisodes'',''WSWBestIdx'',''WSEpisodes'',''WSBestIdx'',''SWEpisodes'',''SWBestIdx'',''GoodSleepInterval'');'...
'sleepstart = Start(subset(WSEpisodes{WSBestIdx},2))/10000;'...
'[tstarts, SleepStartCounts] = PETH (S, sleepstart , 360, 600, 10, 0);'...
'save(fullfile(basepath,[basename ''_SpikePETHs'']),''SleepStartCounts'');'...
];

varstograb = {'GoodSleepInterval','S','intervals'};

SleepDataset_ExecuteOnDatasets(executestring,varstograb)

