function output = importPhoLabjackServerAnalogEventsCsvFileHelper(filename, dataLines)
%IMPORTFILE Import data from a .csv text file exported by LabjackEventsLoader.py
%  OUTPUT = IMPORTFILE(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  OUTPUT = IMPORTFILE(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  output = importfile("C:\Users\halechr\repo\phoPythonVideoFileParser\results\output.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2019-07-11 16:42:35.345

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options
% Importing Only Running Wheel Data:
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["milliseconds_since_epoch", "AIN0"];
opts.VariableTypes = ["double", "double"];
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
output = readtable(filename, opts);

end