function behavioralBoxData = importCombinedLabjackCSV(filename, dataLines)
%IMPORTFILE Import data from a text file
%  BEHAVIORALBOX47001756020190605COMBINED = IMPORTFILE(FILENAME) reads
%  data from text file FILENAME for the default selection.  Returns the
%  data as a table.
%
%  BEHAVIORALBOX47001756020190605COMBINED = IMPORTFILE(FILE, DATALINES)
%  reads data for the specified row interval(s) of text file FILENAME.
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  behavioralBox47001756020190605Combined = importfile("C:\Users\watsonlab\Desktop\Behavioral Box Data\Labjack Data\behavioralBox_470017560_20190605_001\behavioralBox_470017560_20190605_Combined.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 2019-06-06 02:48:31.148

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [5, Inf];
end

x = importdata(filename);

% Match headers to rest of Pho's code
for a = 1:length(x.colheaders)
	if strmatch(x.colheaders{a}(1:3),'EIO')
		x.colheaders{a}(1) = 'D';
	elseif strmatch(x.colheaders{a},'computerTime')
		x.colheaders{a} = 'Time';
	end
end
behavioralBoxData = array2table(x.data,'VariableNames',x.colheaders);

1;





% %% Setup the Import Options
% opts = delimitedTextImportOptions("NumVariables", 14);
% 
% % Specify range and delimiter
% opts.DataLines = dataLines;
% opts.Delimiter = ",";
% 
% % Specify column names and types
% opts.VariableNames = ["Time", "TEMPERATURE_AIR_K", "Var3", "DIO0", "DIO1", "DIO2", "DIO3", "DIO4", "DIO5", "DIO6", "DIO7", "Var12", "Var13", "Var14"];
% opts.SelectedVariableNames = ["Time", "TEMPERATURE_AIR_K", "DIO0", "DIO1", "DIO2", "DIO3", "DIO4", "DIO5", "DIO6", "DIO7"];
% 
% %Pho
% opts.VariableTypes = ["double", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];
% opts = setvaropts(opts, [3, 12, 13, 14], "WhitespaceRule", "preserve");
% opts = setvaropts(opts, [3, 12, 13, 14], "EmptyFieldRule", "auto");
% 
% %BW
% % opts.VariableTypes = ["datetime", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];
% % opts = setvaropts(opts, [3, 12, 13, 14], "WhitespaceRule", "preserve");
% % opts = setvaropts(opts, [3, 12, 13, 14], "EmptyFieldRule", "auto");
% 
% %opts.VariableTypes = ["datetime", "double", "string", "double", "double", "double", "double", "double", "double", "double", "double", "string", "string", "string"];
% %opts = setvaropts(opts, 1, "InputFormat", "yyyy/MM/dd-HH:mm:ss.SSS");
% opts.ExtraColumnsRule = "ignore";
% opts.EmptyLineRule = "read";
% 
% % Import the data
% behavioralBoxData = readtable(filename, opts);
% % behavioralBoxData = readmatrix(filename, opts);
% end