function channelData = notch60(channelData)
%60Hz filters a 1250hz file, such as a .eeg file.  The data should be in
%the vector input vect
% Notch60HzFor1250Hz made using fdatool

hd = Notch60HzFor1250Hz;
channelData = filter(hd,channelData);        




function Hd = Notch60HzFor1250Hz
%NOTCH60HZFOR1250HZ Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 8.2 and the Signal Processing Toolbox 6.20.
% Generated on: 20-Feb-2015 14:27:35 using fdatool

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in Hz.
Fs = 1250;  % Sampling Frequency

N      = 14;  % Order
Fstop1 = 59;  % First Stopband Frequency
Fstop2 = 61;  % Second Stopband Frequency
Astop  = 80;  % Stopband Attenuation (dB)

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop('N,Fst1,Fst2,Ast', N, Fstop1, Fstop2, Astop, Fs);
Hd = design(h, 'cheby2');

% [EOF]
